rm(list = ls())
DT<-read.delim(file.choose(),sep = ";")
DT$Global_intensity <- as.Date(DT$Date, format="%d/%m/%Y")
DT$Global_active_power <- as.numeric(DT$Global_active_power)
DT$Global_reactive_power <- as.numeric(DT$Global_reactive_power)
DT$Voltage <- as.numeric(DT$Voltage)
DT$Sub_metering_1 <- as.numeric(DT$Sub_metering_1)
DT$Sub_metering_2 <- as.numeric(DT$Sub_metering_2)
DT$Sub_metering_3 <- as.numeric(DT$Sub_metering_3)
DT2<-subset(DT, Global_intensity == "2007-02-01" | Date =="2007-02-02")
FullTimeDate <- paste(DT2$Date, DT2$Time, sep=" ")
FullTimeDate<-dmy_hms(FullTimeDate)
DT3 <- cbind(DT2, FullTimeDate)

png('plot1.png',height = 480,width = 480)
hist((DT2$Global_active_power/1000),col='red',breaks = c(15),main='Global Active Power',xlab = 'Global Active Power (kilowatts)')
dev.off()

